### ISSUE TITLE
[BE] API 수정 요청

### ISSUE THREAD

**Issue by NSRBSG** [Team-ESG/BackEnd#77]
## 만들고자 하는 기능이 무엇인가요?
1. 홈 화면, 아이템 리스트
2. 아이템 상세 페이지
3. 주문내역 상세 페이지

## 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. 
/main/list
유통기한을 안줍니다.
모든 갯수가 마감되었는데, 리스트에 올라옵니다.

2.
/main/item/{item_id}
위치 정보를 안줍니다.
Market ID를 안줍니다.

3.
주문내역 상세 페이지, API 피그마 디자인에 따라 수정 바랍니다.
거래 상태 : [ 거래 실패, 거래 성공, 거래 예약 ... ]
가게 이름, 가게 ID,
주문 일시,
픽업 시간,
가게 전화번호,
아이템, 수량 및 가격

## 예상 작업 시간이 어떻게 되시나요?
ex) 3시간

**Comment by NSRBSG** [comment]
저희 둘이서 얘기할때는 주문내역 상세 페이지는 빼기로 했었던것 같은데 디자인이 완성되어 있네요, 어떻게 할까요?

**Comment by dlwlehd** [comment]
일단 구현은 완료해놨는데 회의 때 얘기 해봐야 할 거 같아용
