### ISSUE TITLE
[BE] bug/장바구니 관련 버그

### ISSUE THREAD

**Issue by NSRBSG** [Team-ESG/BackEnd#89]
## 만들고자 하는 기능이 무엇인가요?
- 장바구니 관련 버그 수정

## 해당 기능을 구현하기 위해 할 일이 무엇인가요?

1. 한 유저가 장바구니에 사과의 전체 개수 4개를 넣었는데, 다른 유저가 사과 2개를 구매함, 이때 장바구니에서 살 수 있는 물품 개수가 2개가 아닌 4개로 받아짐.
2. 장바구니 전체 예약 시 각각 물품마다 원하는 갯수의 2배가 빠지는 현상 발견, 예를 들어 6개의 재고가 있을때, 4개 구매 하면 오류 발생, 3개 구매하면 예약 처리는 되나, 리스트에서 빠지는 현상
3. 장바구니 전체 물품 구매시 장바구니 전체 물품 제거

## 예상 작업 시간이 어떻게 되시나요?
 - 1시간

**Comment by dlwlehd** [comment]
1. 해당 버그는 다른 유저가 이미 4개를 장바구니에 담아 놨기 때문에 shoppingCartListedItemQuantity가 4임은 변하지 않습니다. 하지만 itemQuantity의 값은 변경되기 때문에 실제 예약을 진행 시 구매가 진행이 되지 않습니다. 따라서 살 수 있는 물품 개수를 자동으로 변경하고 싶다면 itemQuantity 값을 참고하면 될 것 같습니다.
2. 해당 버그는 수정하였습니다.
3. 해당 기능은 추가하였습니다.
